### ISSUE TITLE
NullPointerException in Android 5.1 

### ISSUE THREAD

**Issue by Aracem** [Notificare/notificare-push-lib-android#3]
Hello there

Since we updated Notificare in our livestreaming app to version **1.4.1** we started to receive a lot of NullPointerException in the Notificare class **SystemEventReceiver**

This is the Crashlytics report:

```re.notifica.receiver.SystemEventReceiver.onReceive (SystemEventReceiver.java:36)
android.app.LoadedApk$ReceiverDispatcher$Args.run (LoadedApk.java:866)
android.os.Looper.loop (Looper.java:135)
android.app.ActivityThread.main (ActivityThread.java:5254)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:698)```


We use Proguard (perhaps we need to configure something) I telling this because i see the crash is in a Log.d method. It seems to be in the next line, when try to get the Connectivity manager but perhaps due proguard the line is wrong.

Any idea about what is happening?

Thank you so much for your effort and work

**Comment by jjonthemix** [comment]
Hi Aracem, 

A fix for that issue was included in 1.4.2 released a few days ago. Hope that fix your problem. 

Regards,

**Comment by Aracem** [comment]
jjonthemix Can you add to the readme the latest version (or accept me a pull request) ? I think will be very useful for everybody. Right now there isn't any information about this launch in any place, included notificare web page that says latest version is 1.4.1

Thank you for your very quick response :+1:  :smile:

**Comment by jjonthemix** [comment]
Indeed you are right we didn't updated our docs yet. We do tag this repo on every release so the latest tag a ref to the latest release. But we'll make sure we make this info available in our docs as soon as possible. 

Sorry for the inconvenience.

**Comment by jjonthemix** [comment]
Also for future reference there is in notificare-push-lib-android/SDK a CHANGELOG.md, README.md and UPGRADE.md.

**Comment by Aracem** [comment]
Perfect, is in the Changelog where is placed the last version. I saw it in the past but this week i didn't remember where i saw that information.

Thank you @jjonthemix
