### ISSUE TITLE
Activity stack management.

### ISSUE THREAD

**Issue by dadu1** [Notificare/notificare-push-lib-android#5]
I have integrated notificare sdk for android.Currently I have implemented Custom IntentReceiver and when I click on any notification then it will be handle by sdk default handler activity "re.notifica.ui.NotificationActivity".Now I have may questions regarding it.

1) "re.notifica.ui.NotificationActivity" all my running activities and when I press back button of device my app is closed.As per user experience app should navigate back to my app with last activity running.

2) "re.notifica.ui.NotificationActivity" allows parent activity to be set in manifest file but I want to navigate back to my application to screen from where I opened notification.It is not necessary the screen I left was same as parent activity I defined in manifest file.

3) "re.notifica.ui.NotificationActivity" if we also define parent activity then its oncreate method is called means it is newly created.I want my last activity on backpressed with OnResume call.This is very weird behaviour for user experience.

4) Below lollipop there will not be seen multiple task on launcher screen.So to navigate back in app will not possible with current implementation.

Please give me perfect solution to handle above use cases.Thanks in advance.

**Comment by jjonthemix** [comment]
Can you please drop this question in support@notifica.re. We can only provide you support if you have a paid plan. Thanks.
